name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
- uses: everpcpc/cloudflare-dns-action@v1
  with:
    type: "A"
    name: "hello.uses.cf"
    content: "8.8.8.8"
    ttl: 1
    proxied: false
    token: ${{ secrets.CLOUDFLARE_TOKEN }}
    zone: ${{ secrets.CLOUDFLARE_ZONE }}
